# Generated by Django 3.0 on 2022-04-23 11:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cash_on_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_on_delivery',
            name='amounts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cash_on_delivery',
            name='no_of_items',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cash_on_delivery',
            name='orders',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='core.Cart'),
        ),
        migrations.AlterField(
            model_name='cash_on_delivery',
            name='address_type',
            field=models.CharField(blank=True, choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cash_on_delivery',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cash_on_delivery',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
        migrations.AlterField(
            model_name='cash_on_delivery',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cash_on_delivery',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cash_on_delivery',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
